#version 450
layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in;

#include "noise_generator.glsl"

layout(constant_id = 0) const uint kVoxelResolution = 1;
layout(constant_id = 1) const uint kFragmentCount = 1;

layout(std430, binding = 1) buffer uuOctree { uint uOctree[]; };

#define POINTER_MASK 0x3fffffffu;

uvec4 LeafToUvec4(uint val) {
    return uvec4((val & 0xffu), ((val >> 8u) & 0xffu), ((val >> 16u) & 0xffu), ((val >> 24u) & 0x3fu));
}
uint Uvec4ToLeaf(uvec4 vec) {
    return (min(vec.w, 0x3fu) << 24u) | (vec.x & 0xffu) | ((vec.y & 0xffu) << 8u) | ((vec.z & 0xffu) << 16u) |
    0xC0000000u;
}

uint TraverseOctree(in const uvec3 voxel_pos, out bool is_leaf) {
    uint level_dim = kVoxelResolution;
    uvec3 level_pos = voxel_pos;

    uint idx = 0u, cur = 0u;
    do {
        level_dim >>= 1;
        bvec3 cmp = greaterThanEqual(level_pos, uvec3(level_dim));
    idx = cur | uint(cmp.x) | (uint(cmp.y) << 1u) | (uint(cmp.z) << 2u);
    cur = uOctree[idx] & POINTER_MASK; // read node pointer
    level_pos -= uvec3(cmp) * level_dim;
    } while (cur != 0 && level_dim > 1u);
    is_leaf = level_dim == 1u;
    return idx;
}

void main() {
    if (any(greaterThanEqual(gl_GlobalInvocationID.xyz, uvec3(kFragmentCount)))) return;

    uvec3 voxel_pos = gl_GlobalInvocationID.xyz;

    float c = 1.f;
    vec3 fvoxel_pos = vec3(voxel_pos) / float(kVoxelResolution);
    float h = noise(fvoxel_pos);
    vec3 O = vec3(.5f);
    float r = .25f;
    float D = length(O - fvoxel_pos) + .01 * h - r;
    if (D > 0) return;

    bool is_leaf;
    uint idx = TraverseOctree(voxel_pos, is_leaf);
    uint vox_color = 0xf8f8f8;

    if (is_leaf) {
        // tag and color data
        uOctree[idx] = 0xC0000000u | (vox_color & 0xffffffu); // termination
    } else {
        uOctree[idx] = 0x80000000u;
    }
}
