#version 450

#include "ascii.glsl"
#include "quaternion.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer uuAxiom { uint uAxiom[]; };
layout(binding = 1) uniform uuAxiomInfo { uint uAxiomLength, uOffset, uDepth; };
layout(binding = 2) uniform uuTurtleConstants { vec3 _D, _N, _P, _O;
                                                       float uPhi, uStep; };
layout(binding = 3) buffer uuTranslations { vec3 uTranslation[]; };
layout(binding = 4) buffer uuRotations { vec4 uRotation[]; };

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= uOffset) return;

    vec3 D, N, P;

    vec3 translation_stack[1];
    vec4 rotation_stack[1];
    uint branch = 0, terminal = 0;
    vec3 translation = _O + vec3(uTranslation[idx]);
    vec4 rotation = vec4(uRotation[idx]);

    D = normalize(quat_rotate(rotation, _D));
    N = normalize(quat_rotate(rotation, _N));
    P = normalize(quat_rotate(rotation, _P));

    for (uint i = 0; i < uAxiomLength; i++) {
        uint literal = uAxiom[i];
        switch (literal) {
            case ASCII_F:
                // forward
                translation += D * uStep;
                break;
            case ASCII_X:
                // write position
                uint writeIdx = uOffset + uAxiomLength * idx + terminal;
                uTranslation[writeIdx] = translation;
                uRotation[writeIdx] = rotation;
                terminal++;
                break;
            case ASCII_PLUS:
                // right turn
                rotation = quat_mult(rotation, quat_rotate(uPhi, N));
                break;
            case ASCII_MINUS:
                // left turn
                rotation = quat_mult(rotation, quat_rotate(-uPhi, N));
                break;
            case ASCII_LT: // <
                // roll ccw
                rotation = quat_mult(rotation, quat_rotate(-uPhi, D));
                break;
            case ASCII_GT: // >
                // roll cw
                rotation = quat_mult(rotation, quat_rotate(uPhi, D));
                break;
            case ASCII_SQR_BRACKET_OPEN:
                translation_stack[branch] = translation;
                rotation_stack[branch] = rotation;
                branch++;
                break;
            case ASCII_SQR_BRACKET_CLOSE:
                branch--;
                translation = translation_stack[branch];
                rotation = rotation_stack[branch];
                break;
            default:
                // Illegal character will be ignored
                break;
        }
    }
}
