#version 450

#include "ascii.glsl"
#include "quaternion.glsl"

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) readonly buffer uuAxiom { uint uAxiom[]; };
layout(binding = 1) buffer uuAxiomInfo { uint uAxiomLength, uOffset, uDepth, uOctreeLevel, uFragmentCount, uNumTerminals; };
layout(binding = 2) readonly buffer uuTurtleConstants { vec3 _D, _N, _O;
                                               float uPhi, uStep; };
layout(binding = 3) buffer uuTranslations { vec3 uTranslation[]; };
layout(binding = 4) buffer uuRotations { vec4 uRotation[]; };

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= uOffset) return;

    vec3 D, N;

    vec3 translation_stack[1];
    vec4 rotation_stack[1];
    uint branch = 0, terminal = 0, voxel_resolution = (1 << uOctreeLevel);
    vec3 translation = vec3(uTranslation[idx + (uOffset / uNumTerminals)]);
    vec4 rotation = vec4(uRotation[idx + (uOffset / uNumTerminals)]);


    for (uint i = 0; i < uAxiomLength; i++) {
        D = quat_rotate(_D, rotation);
        N = quat_rotate(_N, rotation);
        uint literal = uAxiom[i];
        switch (literal) {
            case ASCII_F:
                // forward
                translation += D * uStep;
                //translation = floor(translation * voxel_resolution) * uStep + uStep * .5f;

                // write position
                uint writeIdx = uOffset + uNumTerminals * idx + terminal;
                uTranslation[writeIdx] = translation;
                uRotation[writeIdx] = rotation;
                terminal++;
                break;
            case ASCII_PLUS:
                // right turn
                rotation = quat_mult(rotation, quat_rotate(-uPhi, N));
                break;
            case ASCII_MINUS:
                // left turn
                rotation = quat_mult(rotation, quat_rotate(uPhi, N));
                break;
            case ASCII_LT: // <
                // roll ccw
                rotation = quat_mult(rotation, quat_rotate(-uPhi, D));
                break;
            case ASCII_GT: // >
                // roll cw
                rotation = quat_mult(rotation, quat_rotate(uPhi, D));
                break;
            case ASCII_SQR_BRACKET_OPEN:
                translation_stack[branch] = translation;
                rotation_stack[branch] = rotation;
                branch++;
                break;
            case ASCII_SQR_BRACKET_CLOSE:
                branch--;
                translation = translation_stack[branch];
                rotation = rotation_stack[branch];
                break;
            default:
                // Illegal character will be ignored
                break;
        }
    }
}
